spring.application.name=SprintBoot_API_Practive_Session10

#Config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_jb_251229_ss10
spring.datasource.username=postgres
spring.datasource.password=1234$

#Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Config logging
#logging.console.enabled=true

#Config swagger-ui
springdoc.swagger-ui.path=/swagger-ui.html

#Config jwt
jwt-secret = lamotchuoibimatdetaorakhoabimatphaidudodaithimoiduoc
# chuoi jwt ton tai trong 10 phút
jwt-expired = 600000
# chuoi refresh jwt : Dùng để cấp lại jwt khi chuỗi jwt cũ hết hạn
# tồn tại trong thời gian 30 ngày
jwt-refresh-expired = 2595000000